kind: pipeline
name: default

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
  - name: build=image
    image: maven:3-jdk-11
    commands:
      - mvnw spring-boot:build-image
  - name: docker-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: vanseverk/spring-drone-harness
      tags: latest